config/routes.rb
Rails.application.routes.draw do

  root to: "tests#index"

  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'users/sessions' }

  resources :tests do
    resources :questions do
      resources :answers
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, except: :index do
        resources :answers, except: :index
      end
    end

    resources :gists, only: :index
  end

  resource :gist, only: :create

  resources :feedbacks, only: %i[new create]

end

app/models/question.rb
class Question < ApplicationRecord

  belongs_to :test, counter_cache: true
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true

  def number
    test.questions.ids.index(id) + 1
  end

end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  THRESHOLD = 85.freeze

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: "Question", optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_update :before_update_set_next_question

  def successful?
    if correct_answers_percentage >= THRESHOLD
      true
    else
      false
    end
  end

  def correct_answers_percentage
    (correct_questions.to_f * 100 / test.questions.count).to_i
  end

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def time_is_over?
    return false if test.time_limit.zero?

    Time.now > self.deadline
  end

  def time_left
    deadline - Time.now
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    unless answer_ids.nil?
      correct_answers.ids.sort == answer_ids.map(&:to_i).sort
    else
      false
    end
  end

  def correct_answers
    current_question.answers.correct
  end

  def before_update_set_next_question
    self.current_question = next_question
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def deadline
    created_at + test.time_limit.minutes
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :set_test_passage, only: %i[show update result]

  def show
    
  end

  def result
    
  end

  def update
    return redirect_to test_passage_path(@test_passage),
                       alert: t('.no_answer') unless params[:answer_ids]

    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed? || @test_passage.time_is_over?
      TestsMailer.completed_test(@test_passage).deliver_now
      operate_badges(@test_passage)
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end

  def operate_badges(test_passage)
    badges = Badges::IssuingBadges.new(test_passage).call
    flash[:notice] = new_badges_message(badges)
  end

  def new_badges_message(badges)
    unless badges.empty?
      Badges::FlashMessages::NewBadgesMessage.call(badges.count)
    end
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper

  def results_header(test_passage)
    if test_passage.successful?
      t('.success', test_title: test_passage.test.title)
    else
      t('.fail', test_title: test_passage.test.title)
    end
  end

  def test_results(test_passage)
    if test_passage.successful?
      "<p>
         #{t('.result')}
         <span class='success'>
           #{test_passage.correct_answers_percentage}%
         </span>
       </p>".html_safe
    else
      "<p>
         #{t('.result')} 
         <span class='failure'>
           #{test_passage.correct_answers_percentage}%
         </span>
       </p>".html_safe
    end
  end

end

app/views/test_passages/result.html.erb
<div class="container-fluid text-center mt-5">
  <h1><%= results_header(@test_passage) %></h1>

  <h3>
    <%= test_results(@test_passage) %>
  </h3>

  <%= link_to t('.to_tests'), tests_path, class: "btn btn-dark" %>
</div>

app/views/test_passages/show.html.erb
<div class="container-fluid mt-4">
  <h1 class="text-center"><%= t('.passing', test_title: @test_passage.test.title) %></h1>

  <h5 class="text-center mt-2">
    <%= t('.questions_count', count: @test_passage.test.questions.count) %>
  </h5>

  <table class="table table-bordered border-dark mt-3">
    <div class="timer" id="timer" data-time-left="<%= @test_passage.time_left %>"></div>

    <tr>
      <th>
        <h5 class="text-center">
          <%= t('.question_number', number: @test_passage.current_question.number) %>
        </h5>
      </th>
    </tr>

    <tr>
      <th>
        <%= content_tag :div,
                        class: "progress-bar mb-1",
                        data: { questions_count: @test_passage.test.questions.count,
                                current_question_number: @test_passage.current_question.number } do %>
            <div class="progress-bar-line"></div>
        <% end %>

        <p><%= link_to icon('github', t('.create_gist')), gist_path, class: "btn btn-outline-dark mt-2", method: :post %></p>
        <h5 class="mb-2 d-block">
          <%= @test_passage.current_question.body %>
        </h5>

        <%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>

          <%= form.collection_check_boxes :answer_ids,
                                          @test_passage.current_question.answers,
                                          :id,
                                          :body,
                                          include_hidden: false do |b| %>
            <p class="form-check">
              <%= b.check_box id: "answer_ids_#{b.object.id}", class: "form-check-input" %>
              <%= b.label class: "form-check-label" %>
            </p>
          <% end %>

          <p><%= form.submit t('.next'), class: "btn btn-dark mt-3" %></p>
        <% end %>
      </th>
    </tr>
  </table>
</div>