config/routes.rb
Rails.application.routes.draw do

  root to: "tests#index"

  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'users/sessions' }

  resources :tests do
    resources :questions do
      resources :answers
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, except: :index do
        resources :answers, except: :index
      end
    end

    resources :gists, only: :index
  end

  resource :gist, only: :create

  resources :feedbacks, only: %i[new create]

end

app/models/admin.rb
class Admin < User
end

app/models/answer.rb
class Answer < ApplicationRecord

  MAX_ANSWERS_COUNT = 4

  belongs_to :question

  validates :body, presence: true

  validate :validate_question_answers_count_limit, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def validate_question_answers_count_limit
    errors.add(:question, "cannot contain more than 4 answers") if
    question.answers.count >= MAX_ANSWERS_COUNT
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :tests

  validates :title, presence: true

  default_scope { order(title: :asc) }
  
end

app/models/feedback.rb
class Feedback < ApplicationRecord

  belongs_to :user

  validates :title, :body, presence: true

end

app/models/gist.rb
class Gist < ApplicationRecord

  belongs_to :user
  belongs_to :question
  
  validates :url, presence: true

end

app/models/question.rb
class Question < ApplicationRecord

  belongs_to :test, counter_cache: true
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true

  def number
    test.questions.ids.index(id) + 1
  end

end

app/models/test.rb
class Test < ApplicationRecord

  belongs_to :category
  belongs_to :creator, class_name: "User", foreign_key: "creator_id"
  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages

  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  scope :by_category, -> (name) { joins(:category).where("categories.title = ?", name) }
  scope :by_level, -> (level) { where(level: level) }
  scope :level_unknown, -> { by_level(0) }
  scope :easy, -> { by_level(1) }
  scope :medium, -> { by_level(2) }
  scope :hard, -> { by_level(3) }
  scope :ready, -> { where("questions_count > ?", 0).where(active: true) }
  
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  THRESHOLD = 85.freeze

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: "Question", optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_update :before_update_set_next_question

  def successful?
    if correct_answers_percentage >= THRESHOLD
      true
    else
      false
    end
  end

  def correct_answers_percentage
    (correct_questions.to_f * 100 / test.questions.count).to_i
  end

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def time_is_over?
    return false if test.time_limit.zero?

    Time.now > self.deadline
  end

  def time_left
    deadline - Time.now
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    unless answer_ids.nil?
      correct_answers.ids.sort == answer_ids.map(&:to_i).sort
    else
      false
    end
  end

  def correct_answers
    current_question.answers.correct
  end

  def before_update_set_next_question
    self.current_question = next_question
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def deadline
    created_at + test.time_limit.minutes
  end
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable,
         :registerable,
         :confirmable,
         :recoverable,
         :rememberable,
         :validatable

  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages
  has_many :created_tests, class_name: "Test", foreign_key: "creator_id"
  has_many :gists, dependent: :destroy
  has_many :feedbacks, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true
  validates :password_confirmation, presence: true

  def completed_tests_by_level(level)
    tests.by_level(level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    is_a?(Admin)
  end
  
end

app/models/user_test.rb
class UserTest < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController

  before_action :set_test_passage, only: :create

  def create
    gist = GistQuestionService.new(@test_passage.current_question)
    result = gist.call

    if gist.success?
      current_user.gists.create(question: @test_passage.current_question, url: result.html_url)
      flash[:notice] = t('.success', url: result.html_url)
    else
      flash[:alert] = t('.failure')
    end

    redirect_to test_passage_path(@test_passage)
  end

  private

  def set_test_passage
    @test_passage = TestPassage.last
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController

  before_action :set_test, only: %i[start]

  def index
    @tests = Test.ready
  end

  def start
    current_user.tests.push(@test)

    redirect_to test_passage_path(current_user.test_passage(@test))
  end

  private

  def set_test
    @test = Test.find(params[:id])
  end

end

app/helpers/answers_helper.rb
module AnswersHelper

  def answer_header(current_question, answer)
    if answer.new_record?
      t('.create')
    else
      t('.edit')
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  FLASH_TYPES = { notice: 'alert-success', alert: 'alert-danger' }.freeze

  def current_year
    t('.current_year', year: Time.current.year)
  end

  def github_url(author, repo)
    link_to "GitHub", "https://github.com/#{author}/#{repo}"
  end

  def school_url
    link_to t('.school_url'), "https://thinknetica.com/",
            target: :blank
  end

  def show_flash
    flash.map do |flash_type, message|
      content_tag :p, message, class: "alert #{FLASH_TYPES[flash_type.to_sym]}"
    end.join.html_safe
  end

  def icon(name, text)
    content_tag :i, text, class: "bi bi-#{name}"
  end

  def select_language(lang)
    url_for(lang: lang.to_sym)
  end

end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/gists_helper.rb
module GistsHelper

  def link_to_gist(url)
    link_to url.split('/').last, url, target: '_blank'
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper

  def question_header(test, question)
    if question.new_record?
      t('.create')
    else
      t('.edit')
    end
  end

end

app/helpers/test_passages_helper.rb
module TestPassagesHelper

  def results_header(test_passage)
    if test_passage.successful?
      t('.success', test_title: test_passage.test.title)
    else
      t('.fail', test_title: test_passage.test.title)
    end
  end

  def test_results(test_passage)
    if test_passage.successful?
      "<p>
         #{t('.result')}
         <span class='success'>
           #{test_passage.correct_answers_percentage}%
         </span>
       </p>".html_safe
    else
      "<p>
         #{t('.result')} 
         <span class='failure'>
           #{test_passage.correct_answers_percentage}%
         </span>
       </p>".html_safe
    end
  end

end

app/helpers/tests_helper.rb
module TestsHelper
  TEST_LEVELS = { 0 => 'unknown', 1 => 'Easy', 2 => 'Medium', 3 => 'Hard' }.freeze

  def test_level(test)
    TEST_LEVELS[test.level] || 'Insane!'
  end

  def test_header(test)
    if test.new_record?
      t('.create')
    else
      t('.edit')
    end
  end

  def timer(test)
    test.time_limit.zero? ? t('admin.tests.test.no_time_limit') : test.time_limit.to_s
  end
end

app/views/admin/_nav.html.erb
<nav class="navbar navbar-dark bg-primary">
  <div class="container-fluid">
    <%= link_to "TestGuru", root_path, class: "navbar-brand fs-4 mx-5" %>

    <div class="nav-item">
      <span class="btn btn-primary disabled">
        <%= t('.welcome') %><%= current_user.email %>
      </span>

      <span class="nav-item dropdown">
        <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
          <%= t('.select') %>
        </button>

        <ul class="dropdown-menu">
          <li><button class="dropdown-item" type="button">
            <%= link_to t('.en'), select_language(:en), class: "nav-link active" %>
          </button></li>

          <li><button class="dropdown-item" type="button">
            <%= link_to t('.ru'), select_language(:ru), class: "nav-link active" %>
          </button></li>
        </ul>
      </span>

      <button type="button" class="btn btn-primary">
        <%= link_to t('.log_out'), destroy_user_session_path,
                                   method: :delete,
                                   class: "nav-link active" %>
      </button>
    </div>
  </div>
</nav>

app/views/badges/_user_badge.html.erb
<tr class="text-center align-middle">
  <td>
    <%= image_tag "#{badge.image_name}", height: 75 %>
    <br>
    <%= badge.name %>
    <br>
  </td>
  <td><%= badge.description %></td>
</tr>

app/views/badges/user_badges.html.erb
<div class="container">
  <% if @user_badges.any? %>
    <table class="table mt-5">
      <thead class="table-dark text-center">
        <tr>
          <td colspan="2"><%= t('.my_badges') %></td>
        </tr>
      </thead>

      <tbody>
        <%= render @user_badges %>
      </tbody>
    </table>

    <%= render 'show_all_badges' %>
  <% else %>
    <h1 class="text-center align-middle mt-5"><%= t('.no_badges') %></h1>
    <%= render 'show_all_badges' %>
  <% end %>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

    <title>Admin Panel</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application'%>
  </head>

  <body class="d-flex flex-column min-vh-100">
    <%= render 'admin/nav' %>
    
    <%= show_flash %>

    <%= yield %>
    
    <%= render 'shared/footer' %>

    <script>
      var translations = <%= raw(I18n.t('admin.tests.test',
                                        locale: I18n.locale,
                                        default: {}).to_json) %>
    </script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

    <title>TestGuru</title>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column min-vh-100">
    <%= render 'shared/header' %>

    <%= show_flash %>

    <%= yield %>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= content_tag :div,
                  class: "resource-errors",
                  data: { resource_id: resource.id } do %>
    <h2><%= pluralize(resource.errors.count, 'error') %> detected:</h2>

    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer py-3 bg-light">
  <div class="container d-flex justify-content-between align-items-center">
    <div>
      <p>
        <%= current_year %> |
        <%= t('.author') %> |
        <%= github_url('beast8357', 'test-guru') %> <br>
        <%= t('.description') %> |
        <%= school_url %>
      </p>
    </div>
    <div class="text-right">
      <%= link_to t('.feedback'), new_feedback_path %>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "TestGuru", root_path, class: "navbar-brand fs-4 mx-5" %>

    <div class="nav-item">
      <% if user_signed_in?%>
        <span class="btn btn-dark disabled">
          <% if current_user.admin? %>
            <%= t('.welcome', user_name: current_user.email) %>
          <% else %>
            <%= t('.welcome', user_name: current_user.first_name) %>
          <% end %>
        </span>
        <% if current_user.admin?%>
        <button type="button" class="btn btn-dark">
          <%= link_to t('.admin_panel'), admin_tests_path,
                                         class: "nav-link active" %>
        </button>
        <% end %>

        <%= render 'shared/select_language' %>

        <button type="button" class="btn btn-dark">
          <%= link_to t('.log_out'), destroy_user_session_path,
                                     method: :delete,
                                     class: "nav-link active" %>
        </button>
      <% else %>
        <%= render 'shared/select_language' %>

        <button type="button" class="btn btn-dark">
          <%= link_to t('.log_in'), new_user_session_path,
                                    class: "nav-link active" %>
        </button>

        <button type="button" class="btn btn-dark">
          <%= link_to t('.sign_up'), new_user_registration_path,
                                     class: "nav-link active" %>
        </button>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_select_language.html.erb
<span class="nav-item dropdown">
  <button type="button" class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
    <%= t('.select') %>
  </button>

  <ul class="dropdown-menu">
    <li><button class="dropdown-item" type="button">
      <%= link_to t('.en'), select_language(:en), class: "nav-link active" %>
    </button></li>

    <li><button class="dropdown-item" type="button">
      <%= link_to t('.ru'), select_language(:ru), class: "nav-link active" %>
    </button></li>
  </ul>
</span>

app/views/shared/_test_question_deleter.html.erb
<%= link_to 'Delete',
            test_question_path(test, question),
            method: :delete,
            data: { confirm: 'Are you sure you want to delete this question?' } %>