config/routes.rb
Rails.application.routes.draw do

  root to: "tests#index"

  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'users/sessions' }

  resources :tests do
    resources :questions do
      resources :answers
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, except: :index do
        resources :answers, except: :index
      end
    end

    resources :gists, only: :index
  end

  resource :gist, only: :create

  resources :feedbacks, only: %i[new create]

end

app/models/question.rb
class Question < ApplicationRecord

  belongs_to :test, counter_cache: true
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true

  def number
    test.questions.ids.index(id) + 1
  end

end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController

  helper_method :current_test

  before_action :find_question, only: %i[show edit update destroy]

  def show
    
  end

  def new
    @question = current_test.questions.new
  end

  def edit
    
  end

  def create
    @question = current_test.questions.new(question_params)

    if @question.save
      redirect_to admin_test_path(current_test)
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to admin_test_path(current_test)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy

    redirect_to admin_test_path(current_test)
  end

  private

  def current_test
    @current_test ||= Test.find(params[:test_id])
  end

  def find_question
    @question = current_test.questions.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:body)
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper

  def question_header(test, question)
    if question.new_record?
      t('.create')
    else
      t('.edit')
    end
  end

end

app/views/admin/questions/_form.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-3">
      <h2><%= question_header(current_test, @question) %></h2>

      <%= form_with model: [:admin, current_test, @question], local: true do |form| %>
        <%= render 'shared/errors', resource: @question %>

        <p>
          <%= form.label :body %><br>
          <%= form.text_area :body, placeholder: true, rows: 7, cols: 60 %>
        </p>

        <p><%= form.submit class: "btn btn-primary" %></p>
      <% end %>

      <%= link_to t('.to_tests'), admin_tests_path, class: "btn btn-primary" %>
      <%= link_to t('.back'), admin_test_path(current_test), class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/admin/questions/_question.html.erb
<tr class="text-center">
  <td class="align-middle"><%= question.body %></td>
  <td class="align-middle">
    <%= link_to t('.show'),
                admin_test_question_path(question.test, question),
                class: "btn btn-primary" %>
  </td>
  <td class="align-middle">
    <%= link_to t('.edit'),
                edit_admin_test_question_path(question.test, question),
                class: "btn btn-primary" %>
  </td>
  <td class="align-middle">
    <%= link_to t('.delete'),
                admin_test_question_path(question.test, question),
                method: :delete,
                data:   { confirm: 'Are you sure?' },
                class: "btn btn-primary" %>
  </td>
</tr>

app/views/admin/questions/edit.html.erb
<%= render 'form' %>

app/views/admin/questions/new.html.erb
<%= render 'form' %>

app/views/admin/questions/show.html.erb
<div class="container mt-3">
  <h3 class="mb-2"><%= t('.header', test_title: @question.test.title) %></h3>

  <h3><%= @question.body %></h3>

  <div class="table-responsive">
    <table class="table table-bordered border-dark mt-2">
      <tr>
        <th class="text-center"><%= t('.answers') %></th>
        <th class="text-center" colspan="3"><%= t('.actions') %></th>
      </tr>

      <%= render @question.answers %>
    </table>
  </div>
</div>

<div class="container">
  <%= link_to t('.new_answer'), new_admin_test_question_answer_path(current_test, @question), class: "btn btn-primary" %>
</div>

<div class="container text-center">
  <p>
    <%= link_to t('.to_tests'), admin_tests_path, class: "btn btn-primary" %>
    <%= link_to t('.back'), admin_test_path(current_test), class: "btn btn-primary" %>
  </p>
</div>